language: python
python: 2.7
install:
  - pip install -r requirements/requirements.txt --upgrade
  - pip install -r requirements/devrequirements.txt --upgrade --allow-external inotifyx --allow-unverified inotifyx
env:
  - DJANGO_SETTINGS_MODULE=blog.conf.settings
script: make travisci
after_success:
    coveralls
